application: gu-pasteup
version: 1
runtime: python
api_version: 1

handlers:

- url: /content
  static_dir: content

- url: /css
  static_dir: css

- url: /docs
  static_dir: docs

- url: /js
  static_dir: js

- url: /less
  static_dir: less